import type { EnemyDef } from './types.js'
import { buildingDamageFromSiegeMultiplier, combatBalance, enemyHpFromTtkUnits, enemySpeedFromBase } from './combatBalance.js'

const attackInterval = {
  normal: 1.2,
  fast: 1,
  heavy: 1.4,
  boss: 1.5
} as const

export const enemies = [
  {
    id: 'ember_grunt',
    name: '火渣兵',
    role: 'normal',
    directorCost: 1,
    hp: enemyHpFromTtkUnits(combatBalance.enemyTtkUnits.normal),
    speed: enemySpeedFromBase(0.58),
    buildingDamage: buildingDamageFromSiegeMultiplier(0.32, attackInterval.normal),
    attackInterval: attackInterval.normal,
    baseDamage: 1,
    blockable: true,
    flying: false,
    tags: ['normal', 'ground'],
    special: '无特殊能力，作为基础压力单位。',
    counterBy: ['melee_turret', 'ranged_turret'],
    visualRule: '小体型、暗红轮廓、无护甲，作为最基础读法。',
    firstWave: 1,
    status: 'draft'
  },
  {
    id: 'spark_runner',
    name: '火星疾行者',
    role: 'fast',
    directorCost: 2,
    hp: enemyHpFromTtkUnits(combatBalance.enemyTtkUnits.fast),
    speed: enemySpeedFromBase(0.95),
    buildingDamage: buildingDamageFromSiegeMultiplier(0.24, attackInterval.fast),
    attackInterval: attackInterval.fast,
    baseDamage: 1,
    blockable: true,
    flying: false,
    tags: ['fast', 'ground'],
    special: '高速冲线，考验防御机关和攻速补强。',
    counterBy: ['lava_wall', 'melee_turret', 'attack_speed_up', 'emergency_freeze'],
    visualRule: '细长剪影、拖尾火星、移动动画更急促。',
    firstWave: 2,
    status: 'draft'
  },
  {
    id: 'basalt_smasher',
    name: '玄武重击者',
    role: 'heavy_attack',
    directorCost: 3,
    hp: enemyHpFromTtkUnits(combatBalance.enemyTtkUnits.heavy_attack),
    speed: enemySpeedFromBase(0.42),
    buildingDamage: buildingDamageFromSiegeMultiplier(1, attackInterval.heavy),
    attackInterval: attackInterval.heavy,
    baseDamage: 1,
    blockable: true,
    flying: false,
    tags: ['heavy_attack', 'ground', 'building_breaker'],
    special: '对魔导具造成高伤害，逼玩家修复、防御或补单体输出。',
    counterBy: ['ranged_turret', 'laser_turret', 'emergency_repair_all', 'defense_taunt_wall'],
    visualRule: '宽大厚重剪影、黑灰石甲、攻击魔导具时有重击前摇。',
    firstWave: 3,
    status: 'draft'
  },
  {
    id: 'ash_wing',
    name: '灰烬飞翼',
    role: 'flying',
    directorCost: 3,
    hp: enemyHpFromTtkUnits(combatBalance.enemyTtkUnits.flying),
    speed: enemySpeedFromBase(0.72),
    buildingDamage: 0,
    attackInterval: 0,
    baseDamage: 1,
    blockable: false,
    flying: true,
    tags: ['flying', 'anti_block'],
    special: '飞行单位，无视防御机关，检验索敌魔导具覆盖和对空强化。',
    counterBy: ['ranged_turret', 'attack_anti_air_focus'],
    visualRule: '悬浮高度明显，地面阴影与翅膀轮廓区分飞行属性。',
    firstWave: 4,
    status: 'draft'
  },
  {
    id: 'volcano_core_beast',
    name: '火山核心兽',
    role: 'boss',
    directorCost: 99,
    hp: enemyHpFromTtkUnits(combatBalance.enemyTtkUnits.boss),
    speed: enemySpeedFromBase(0.3),
    buildingDamage: buildingDamageFromSiegeMultiplier(1.2, attackInterval.boss),
    attackInterval: attackInterval.boss,
    baseDamage: 3,
    blockable: true,
    flying: false,
    tags: ['boss', 'ground', 'building_breaker'],
    special: '最终检验单位，移动慢、拆魔导具强、触底伤害高。',
    counterBy: ['ranged_turret', 'laser_turret', 'attack_power_up', 'emergency_repair_all'],
    visualRule: '大体型核心怪，胸口熔岩亮点作为弱点提示。',
    firstWave: 5,
    status: 'draft'
  }
] as const satisfies readonly EnemyDef[]
